name: PR LLM Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full git history for local git operations

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }} || true

      - name: Run LLM PR Review
        uses: ./.github/actions/llm-pr-bot
        with:
          llm_provider: claude
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_model: ${{ vars.CLAUDE_MODEL }}  # Uses repository variable

          review_mode: agentic_tools
          review_output_mode: log

          language: move
          extra_instructions: